builders:
  mlg_logger:
    target: ":generator"
    import: "package:mlg_logger/builder.dart"
    builder_factories: ["generateLogger"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
